Add new version of aws provider
WhistleLabs/dockerfile-ci pull request #34
Opened 2018-08-28 04:24 UTC by kjonick1

This is just first update.  I'll add the glibc updates as well.

But didn't know if we wanted to keep adding new versions of aws providers.  We have several now.  version 1.18.0 was added recently and used in 5 locations.  I'm wondering if I should replace those with latest, or just keep adding new versions for just stacks affected.

2018-08-28 04:47 UTC, pickgr commented
Yes.  Please see the comments I made in JIRA earlier today

2018-08-28 14:33 UTC, pickgr requested changes
Let's see if we can't consolidate a few of these versions and still keep this containable within the sprint.

2018-08-29 04:08 UTC, kjonick1 commented
Sorry, didn't see your post.  Since 1.18 is only in a couple projects, we'll remove that version and replace with 1.33.  

Also, updated the sgerrand.rsa.pub location.

2018-08-30 03:55 UTC, kjonick1 commented
@pickgr New changes replacing 1.18 with latest.

2018-08-30 04:49 UTC, pickgr approved these changes

2018-08-30 13:53 UTC, merged